"""
Pydantic request/response models for the API layer (Phase 5).
"""

from typing import Literal, Optional

from pydantic import BaseModel, Field


# ======================================================
# /v1/ask REQUEST
# ======================================================


class AskRequest(BaseModel):
    """
    Request body for the RAG question-answering endpoint.
    """

    question: str = Field(
        ...,
        min_length=1,
        description="Question to ask against the indexed documents.",
    )

    retrieval_mode: Literal[
        "hybrid",
        "dense_only",
    ] = "hybrid"

    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=50,
        description="Maximum number of chunks to keep after retrieval.",
    )


# ======================================================
# CITATION
# ======================================================


class Citation(BaseModel):
    """
    A citation generated by the RAG pipeline and verified
    against the referenced retrieved chunk.
    """

    marker: str

    chunk_id: str

    source_document: str

    section_heading: Optional[str] = None

    supported: bool

    excerpt: str


# ======================================================
# CONFIDENCE
# ======================================================


class ConfidenceBreakdown(BaseModel):
    """
    Confidence scores calculated for the generated answer.
    """

    retrieval_confidence: float

    citation_coverage: float

    answer_completeness: float

    composite: float


# ======================================================
# RETRIEVED CHUNK
# ======================================================


class RetrievedChunk(BaseModel):
    """
    UI-friendly representation of a retrieved chunk.
    """

    rank: int

    chunk_id: str

    score: Optional[float] = None

    source_document: str

    section_heading: Optional[str] = None

    preview: str


# ======================================================
# PERFORMANCE METRICS
# ======================================================


class PerformanceMetrics(BaseModel):
    """
    Latency breakdown for each RAG pipeline stage.

    All values are measured in milliseconds.
    """

    retrieval_ms: float = 0.0

    generation_ms: float = 0.0

    verification_ms: float = 0.0

    confidence_ms: float = 0.0

    total_ms: float = 0.0


# ======================================================
# TOKEN USAGE
# ======================================================


class TokenUsage(BaseModel):
    """
    Token usage reported by the generation provider.

    Values may be unavailable for some local model providers.
    """

    prompt_tokens: Optional[int] = None

    completion_tokens: Optional[int] = None

    total_tokens: Optional[int] = None


# ======================================================
# /v1/ask RESPONSE
# ======================================================


class AskResponse(BaseModel):
    """
    Structured response returned by the RAG query endpoint.
    """

    answer: str

    citations: list[Citation]

    confidence: ConfidenceBreakdown

    retrieved_chunks: list[RetrievedChunk]

    timings: Optional[PerformanceMetrics] = None

    usage: Optional[TokenUsage] = None

    is_fallback: bool = False


# ======================================================
# /v1/documents
# ======================================================


class DocumentSummary(BaseModel):
    """
    Summary of one indexed source document.
    """

    source_file: str

    num_chunks: int

    chunking_strategies_used: list[str]

    last_indexed_at: str


class DocumentListResponse(BaseModel):
    """
    Response containing all indexed documents.
    """

    documents: list[DocumentSummary]


# ======================================================
# /v1/ingest
# ======================================================


class IngestRequest(BaseModel):
    """
    Request body for document ingestion.
    """

    file_paths: list[str]

    chunking_strategy: Literal[
        "fixed_size",
        "recursive_structure",
        "semantic",
    ] = "recursive_structure"


class IngestResponse(BaseModel):
    """
    Result of a document ingestion operation.
    """

    ingested_files: list[str]

    chunks_created: int

    duplicates_skipped: int